<?php

namespace ComensalesBundle\Repository;

/**
 * DetalleEnfermedadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleEnfermedadRepository extends \Doctrine\ORM\EntityRepository
{
}
