<?php

namespace ComensalesBundle\Repository;

/**
 * EstadoTarjetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoTarjetaRepository extends \Doctrine\ORM\EntityRepository
{
}
