<?php

namespace ComensalesBundle\Repository;

use ComensalesBundle\Entity\Facultad;

/**
 * FacultadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacultadRepository extends \Doctrine\ORM\EntityRepository
{
    public function obtenerFacultadId($nombreFacultad)
    {
        $id = $this->getEntityManager()
                    ->getRepository(Facultad::class)
                    ->findBynombreCortoFacultad($nombreFacultad);
               
        if($id != null && !empty($id))
        {
             $id = $id[0]->getId();
        }
        return $id;
    }
    
}
