<?php

namespace ComensalesBundle\Repository;

/**
 * FacultadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacultadRepository extends \Doctrine\ORM\EntityRepository
{
}
