<?php

namespace ComensalesBundle\Repository;

/**
 * FormularioIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormularioIRepository extends \Doctrine\ORM\EntityRepository
{
}
