<?php

namespace ComensalesBundle\Repository;

/**
 * HistorialConsumosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistorialConsumosRepository extends \Doctrine\ORM\EntityRepository
{
}
