<?php

namespace ComensalesBundle\Repository;

/**
 * HistorialRecargasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistorialRecargasRepository extends \Doctrine\ORM\EntityRepository
{
}
