<?php

namespace ComensalesBundle\Repository;

/**
 * ItemConsumoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemConsumoRepository extends \Doctrine\ORM\EntityRepository
{
}
