<?php

namespace ComensalesBundle\Repository;

/**
 * ItemRecargaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRecargaRepository extends \Doctrine\ORM\EntityRepository
{
}
