<?php

namespace ComensalesBundle\Repository;

/**
 * MotivoRechazoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotivoRechazoRepository extends \Doctrine\ORM\EntityRepository
{
}
