<?php

namespace ComensalesBundle\Repository;

/**
 * TipoEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEstadoRepository extends \Doctrine\ORM\EntityRepository
{
}
