<?php

namespace ComensalesBundle\Repository;

use ComensalesBundle\Entity\TipoEstado;
/**
 * TipoEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEstadoRepository extends \Doctrine\ORM\EntityRepository
{
    public function obtenerEstadoSolicitudId($nombreEstado)
    {
        $id = $this->getEntityManager()
                   ->getRepository(TipoEstado::class)
                   ->findBynombreEstado($nombreEstado);
               
        if($id != null && !empty($id))
        {
             $id = $id[0]->getId();
        }
        return $id;
    }
}
