<?php

namespace ComensalesBundle\Repository;

use ComensalesBundle\Entity\TipoComensal;
/**
 * TipoComensalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoComensalRepository extends \Doctrine\ORM\EntityRepository
{
    public function obtenerTipoComensalId($tipo)
    {
        $id = $this->getEntityManager()
                   ->getRepository(TipoComensal::class)
                   ->findBynombreComensal($tipo);
               
        if($id != null && !empty($id))
        {
             $id = $id[0]->getId();
        }
        return $id;
    }
}
