<?php

namespace ComensalesBundle\Repository;

/**
 * TipoRechazoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRechazoRepository extends \Doctrine\ORM\EntityRepository
{
}
