comensales:
    resource: "@ComensalesBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path:     /login
    defaults: { _controller: ComensalesBundle:Default:login }
 
login_check:
    path: /login_check
logout:
    path: /logout