# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
#   sino se encuentra, se muestra 'username colund not found
    hide_user_not_found: false 
    encoders:
        ComensalesBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 4
            
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: ComensalesBundle:Usuario
                property: nombreUsuario
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
#        secured_area:
#            pattern:    ^/
#            anonymous: ~
#            http_basic:
#                realm: "Ingreso a la web app"

        main:
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: logout
                target: /login
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/ventas, roles: ROLE_VENDEDOR_PREDIO }
#        - { path: ^/login, roles: ROLE_VENDEDOR_PREDIO }
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
